services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: jobcore-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: jobcore
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - jobcore-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: jobcore-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - jobcore-network

  # Typesense Search Engine
  typesense:
    image: typesense/typesense:0.25.2
    container_name: jobcore-typesense
    restart: unless-stopped
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    networks:
      - jobcore-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobcore-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
      - typesense
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/jobcore?authSource=admin
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
      - TYPESENSE_API_KEY=xyz
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=redis123
      # Add other environment variables as needed
      - SUPABASE_URL=${VITE_SUPABASE_URL}
      - SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - jobcore-network

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: jobcore-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - frontend_node_modules:/app/node_modules
    networks:
      - jobcore-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: jobcore-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - jobcore-network

volumes:
  mongodb_data:
  redis_data:
  typesense_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  jobcore-network:
    driver: bridge 